### ISSUE TITLE
[Question] Having a wandb Video object, how can I log it into a StreamTable?

### ISSUE THREAD

**Issue by phcerdan** [wandb/weave#1085]
The following attempt is not working... I wonder if I need to convert the Video to something weave can understand first?
 ``` 
        target_gif = wandb.Video(target_array, fps=10, caption=target_caption)
        gifs = {f"gif_target_{sampling_plane}": target_gif}
        
        self.stream_table = StreamTable(
            table_name=f"{self.mode}_{self.run.id}",
            entity_name=self.run.entity,
            project_name=self.run.project,
        )
        
        self.stream_table.log([gifs])
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "source/.venv/lib/python3.11/site-packages/weave/wandb_interface/wandb_stream_table.py", line 287, in _thread_body
    self._flush()
  File "source/.venv/lib/python3.11/site-packages/weave/wandb_interface/wandb_stream_table.py", line 269, in _flush
    super().log(log_payload)
  File "source/.venv/lib/python3.11/site-packages/weave/wandb_interface/wandb_stream_table.py", line 199, in log
    self._log_row(row)
  File "source/.venv/lib/python3.11/site-packages/weave/wandb_interface/wandb_stream_table.py", line 221, in _log_row
    payload = row_to_weave(row_copy, self._artifact)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "source/.venv/lib/python3.11/site-packages/weave/wandb_interface/wandb_stream_table.py", line 345, in row_to_weave
    return {key: obj_to_weave(value, artifact) for key, value in row.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "source/.venv/lib/python3.11/site-packages/weave/wandb_interface/wandb_stream_table.py", line 345, in <dictcomp>
    return {key: obj_to_weave(value, artifact) for key, value in row.items()}
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "source/.venv/lib/python3.11/site-packages/weave/wandb_interface/wandb_stream_table.py", line 368, in obj_to_weave
    return leaf_to_weave(obj, artifact)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "source/.venv/lib/python3.11/site-packages/weave/wandb_interface/wandb_stream_table.py", line 395, in leaf_to_weave
    res = storage.to_python(leaf, None, ref_persister_artifact)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "source/.venv/lib/python3.11/site-packages/weave/storage.py", line 397, in to_python
    wb_type = types.type_of_with_refs(obj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "source/.venv/lib/python3.11/site-packages/weave/weave_types.py", line 1917, in type_of_with_refs
    return TypeRegistry.type_of(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "source/.venv/lib/python3.11/site-packages/weave/weave_types.py", line 162, in type_of
    raise errors.WeaveTypeError("no Type for obj: (%s) %s" % (type(obj), obj))
weave.errors.WeaveTypeError: no Type for obj: (<class 'wandb.sdk.data_types.video.Video'>) <wandb.sdk.data_types.video.Video object at 0x715b0d40a7d0>

```

**Comment by tssweeney** [comment]
Hello @phcerdan  , thank you for your issue report. Unfortunately, we have shifted directions away from the dashboards / stream table product to a more opinionated solution for LLM debugging and tracing. If you are curious, please checkout our docs at https://wandb.me/weave. As such, I am going to close this ticket as we are unlikely to continue development against this feature set at the moment.
