### ISSUE TITLE
BUG: Pydantic AttributeError in Scorer subclass

### ISSUE THREAD

**Issue by nthomsencph** [wandb/weave#1680]
Hi, I'm attempting to implement a subclass of [weave.flow.scorer.Scorer](https://github.com/wandb/weave/blob/master/weave/flow/scorer.py) as you have shown with MultiTaskBinaryClassificationF1 in the same file, line 122. I do this to create a custom `summarize` method for our specific NLP task - which is essentially just a binary classification that we want a lot of metrics for.

Running with `weave-0.50.3` btw.

Here is my implementation
```python 

from typing import Optional, Any
import editdistance
import numpy as np
import weave
from weave.flow.obj import Object

from utils.loggers import logger

class Scorer(Object):

    def score(self, target: Any, model_output: Any) -> Any:
        raise NotImplementedError

    @weave.op()
    def summarize(self, score_rows: weave.WeaveList) -> Optional[dict]:
        raise NotImplementedError


class ELIScorer(Scorer):

    @weave.op()
    def score(self, target: str, model_output: str) -> dict:
        """Score a single example."""

        if not model_output:
            logger.info("Model output is empty")
            model_output = ""

        model_output = self.postprocess(model_output)
        target = self.postprocess(target)

        edit_distance = editdistance.eval(target, model_output)

        exact_match = target == model_output
        correct = exact_match | self.is_correct(target, model_output, edit_distance)

        logger.info(f"{target=} | {model_output=} | {correct=}")
        return {
            "correct": correct,
            "edit_distance": edit_distance,
            "exact_match": exact_match,
            "empty_output": model_output == "",
        }

    @weave.op()
    def summarize(self, score_rows: weave.WeaveList) -> Optional[dict]:
        """Calculate FP, FN, TP, TN, accuracy, precision, recall, f1 and mean edit distance."""

        TP, FP, TN, FN = 0, 0, 0, 0
        edit_distances, empty_outputs = [], []

        for row in score_rows:
            if row["correct"]:
                if row["target"] == "yes":
                    TP += 1
                else:
                    TN += 1
            else:
                if row["target"] == "yes":
                    FN += 1
                else:
                    FP += 1

            edit_distances.append(row["edit_distance"])
            empty_outputs.append(row["empty_output"])

        accuracy = self.compute_accuracy(TP, FP, TN, FN)
        precision = self.compute_precision(TP, FP)
        recall = self.compute_recall(TP, FN)
        f1 = self.compute_f1(precision, recall)
        empty_outputs = sum(empty_outputs)

        return {
            "confusion_matrix": {"TP": TP, "FP": FP, "TN": TN, "FN": FN},
            "metrics": {
                "accuracy": accuracy,
                "precision": precision,
                "recall": recall,
                "f1": f1,
            },
            "mean_edit_distance": np.mean(edit_distances),
            "empty_outputs": empty_outputs,
        }

    def postprocess(self, string: str) -> str:
        return string.strip("'\"").strip().strip(".").lower().strip("answer:").strip()

    def is_correct(self, target: str, model_output: str, edit_distance: int) -> bool:
        return any(
            [
                # match conditions.
                target == model_output,
                model_output.endswith(target),
                model_output.rsplit("\n", 1)[-1].strip().startswith(target),
                edit_distance < 2,
            ]
        )

    def compute_accuracy(self, TP: int, FP: int, TN: int, FN: int) -> float:
        return (TP + TN) / (TP + FP + TN + FN)

    def compute_precision(self, TP: int, FP: int) -> float:
        return TP / (TP + FP)

    def compute_recall(self, TP: int, FN: int) -> float:
        return TP / (TP + FN)

    def compute_f1(self, precision: float, recall: float) -> float:
        return 2 * (precision * recall) / (precision + recall)

```

I call it like so (simplified for readability:

```python 
    import weave
    import asyncio

    from utils.args import ARGS
    from evaluate import Evaluator, eval_function, ELIScorer


    model : Model = ... # Inherits weave model, no issue here.
    eval_examples : list[dict] =  ... # examples, no issue here either

    weave.init(ARGS.EXP_NAME)  # Initialize weave experiment

    # Initialize evaluation
    evaluator = Evaluator(
        name=f"{examples_file}-{ARGS.EXP_NAME}",
         description=f"Evaluation of '{ARGS.model}' on '{examples_file}' dataset.",
         dataset=eval_examples,
         scorers=[ELIScorer],  # <--- Using the custom scorer here
         trials=ARGS.iterations,
    )

    # Run evaluation
    summary, predictions = asyncio.run(
        evaluator.evaluate(model=model, return_rows=True, workers=3)
    )
    # for reference, i sublcasses and overloaded the evaluate method to 
    # to add params `return_rows`and `workers`. See below. These have 
    # absolutely nothing to do with this bug.

```

I get the following error

```bash
(.venv) ➜ ellipses-reasoning git:(rework_to_weave) ✗ python eli/run.py <ARGS>

Logged in as Weights & Biases user: nthomsen.
View Weave data at https://wandb.ai/cbs-nlp/<PROJECT>/weave

Traceback (most recent call last):
  File "<PATH>/eli/run.py", line 67, in <module>
    run()
  File "<PATH>/eli/run.py", line 54, in run
    evaluator.evaluate(model=model, return_rows=True, workers=3)
  File "<PATH>/ellipses-reasoning/lib/python3.12/site-packages/weave/trace/op.py", line 178, in __call__
    return Op.__call__(self, self.arg0, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<PATH>/lib/python3.12/site-packages/weave/trace/op.py", line 81, in __call__
    client.save_nested_objects(inputs_with_defaults)
  File "<PATH>/lib/python3.12/site-packages/weave/weave_client.py", line 574, in save_nested_objects
    self.save_nested_objects(v)
  File "<PATH>/lib/python3.12/site-packages/weave/weave_client.py", line 554, in save_nested_objects
    self.save_nested_objects(v)
  File "<PATH>/lib/python3.12/site-packages/weave/weave_client.py", line 571, in save_nested_objects
    self.save_nested_objects(v)
  File "<PATH>/lib/python3.12/site-packages/weave/weave_client.py", line 576, in save_nested_objects
    self._save_op(obj)
  File "<PATH>/lib/python3.12/site-packages/weave/weave_client.py", line 425, in _save_op
    op_def_ref = self._save_object(op, op.name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<PATH>/lib/python3.12/site-packages/weave/weave_client.py", line 290, in _save_object
    json_val = to_json(val, self._project_id(), self.server)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<PATH>/lib/python3.12/site-packages/weave/trace/serialize.py", line 35, in to_json
    encoded = custom_objs.encode_custom_obj(obj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<PATH>/lib/python3.12/site-packages/weave/trace/custom_objs.py", line 103, in encode_custom_obj
    weave_type.save_instance(obj, art, "obj")
  File "<PATH>/lib/python3.12/site-packages/weave/trace/op_type.py", line 401, in save_instance
    result = get_code_deps(obj.resolve_fn, artifact)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<PATH>/lib/python3.12/site-packages/weave/trace/op_type.py", line 260, in get_code_deps
    var_value = resolve_var(fn, var_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<PATH>/lib/python3.12/site-packages/weave/trace/op_type.py", line 178, in resolve_var
    if fn.__closure__:
       ^^^^^^^^^^^^^^
  File "<PATH>/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 242, in __getattr__
    raise AttributeError(item)
AttributeError: __closure__. Did you mean: '__module__'?
```

In debugging mode, if I find the type and __name__ of `fn` as it hits line 178, it is
`<class 'pydantic._internal._model_construction.ModelMetaclass'>` and `ELIScorer`

***

My adoption of the `Evaluation` class for reference

```python
class Evaluator(Evaluation):
    @weave_op()
    async def evaluate(
        self,
        model: Union[Callable, Model],
        return_rows: bool = False,   # <--- Allows me to return prediction rows
        workers: int = get_weave_parallelism(), # <--- Allows me to set the amount of workers in asyncio
    ) -> dict | tuple[dict, list]:
        async def eval_example(example: dict) -> dict:
            # Function that processes each example
            try:
                eval_row = await self.predict_and_score(model, example)
            except OpCallError as e:
                raise e
            except Exception:
                print("Predict and score failed")
                traceback.print_exc()
                return {"model_output": None, "scores": {}}
            return eval_row

        eval_rows = []
        n_complete = 0
        dataset = cast(Dataset, self.dataset)
        _rows = dataset.rows
        trial_rows = list(_rows) * self.trials

        # Process each row with a semaphore-controlled task
        async for _, eval_row in util.async_foreach(
            sequence=trial_rows, func=eval_example, max_concurrent_tasks=workers # <-- used here
        ):
            n_complete += 1
            print(f"Evaluated {n_complete} of {len(trial_rows)} examples")
            if eval_row is None:
                eval_row = {"model_output": None, "scores": {}}
            if eval_row["scores"] is None:
                eval_row["scores"] = {}
            for scorer in self.scorers or []:
                scorer_name, _, _ = get_scorer_attributes(scorer)
                if scorer_name not in eval_row["scores"]:
                    eval_row["scores"][scorer_name] = {}

            eval_rows.append(eval_row)

        # Summarize the results after all rows have been evaluated
        summary = await self.summarize(eval_rows)
        if return_rows: # <--- flag to decide whether to return row.
            return summary, eval_rows
        return summary

```

To be clear, this worked perfectly with just an evaluation function, like below.

```python

@weave.op()
def eval_function(target: str, model_output: str) -> dict:
    """Evaluate the model output against the target. We
    consider the model output correct if it exactly matches
    the target or if the edit distance between the two
    strings is less than 2."""

    if not model_output:
        logger.info("Model output is empty")
        model_output = ""
        
    model_output = postprocess(model_output)
    edit_distance = editdistance.eval(target, model_output)

    exact_match = target == model_output
    fuzzy_match = edit_distance < 2
    correct = exact_match | fuzzy_match

    logger.info(f"{target=} | {model_output=} | {correct=}")
    return {
        "correct": correct,
        "edit_distance": edit_distance,
        "exact_match": exact_match,
    }
```

**My ask is this:**

* Can you please fix this bug - if it is indeed a bug?

* Can you please add an example to the documentation of how to implement a cusotm Scorer?

* Would you consider adding more out-of-the-box "Scorers" such as `MultiTaskBinaryClassificationF1`? For starters, it could be "BinaryClassificationF1" or "MultiClassClassificationReport" 

Thanks in advance.

**Comment by nthomsencph** [comment]
Any updates on this?

**Comment by jwlee64** [comment]
Hi @nthomsencph, I am going to create a couple tickets for your different asks. 

We can definitely add more docs around custom scorers, and there is already a plan to add more out of the box scorers. I can look into your specific bug today.

**Comment by shawnlewis** [comment]
Hi, very sorry about the delay here.

Make sure you initialize the Scorer like this:
```python
evaluator = Evaluator(
    dataset=[{"item": "x", "target": "y"}],
    scorers=[ELIScorer()],  # <--- Using the custom scorer here
    trials=1,
)
```

And also your ELIScorer needs to inherit from weave.Scorer like this:

```python
from weave import Scorer

class ELIScorer(Scorer):
```

The error message is a bad one from inside the weave framework, we'll make sure we show a better error message there!

**Comment by nthomsencph** [comment]
Thanks! My code works now. 

Perfect. Looking forward to seeing the updates.
