### ISSUE TITLE
weave.trace.errors.OpCallError: Error calling SweetObj.simple_operation: missing a required argument: 'other_val'

### ISSUE THREAD

**Issue by travis-the-dragon** [wandb/weave#2195]
I'm trying to immediately capture feedback from a user, however my calls to the LLMs are wrapped in classes. I modified the code from [this](https://wandb.github.io/weave/guides/tracking/feedback#retrieving-the-call-uuid) doc to show roughly what I'm doing:

```
import weave
weave.init("junk-stuff")

class SweetObj:
    def __init__(self):
        self.name = "sweet"
    
    @weave.op()
    def simple_operation(self, input_value, other_val):
        return f"Processed {input_value}, also {other_val}"
```

When I run this code:

```
result, call = so.simple_operation.call(input_value="example input...", other_val="other item")
```

Python complains I'm not passing `self`:
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dir/.venv/lib/python3.11/site-packages/weave/trace/op.py", line 235, in call
    This function will never raise.  Any errors are captured in the Call object.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "dir/.venv/lib/python3.11/site-packages/weave/trace/op.py", line 146, in _create_call
    inputs = func.signature.bind(*args, **kwargs).arguments
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weave.trace.errors.OpCallError: Error calling SweetObj.simple_operation: missing a required argument: 'self'
```

I can get around it a couple of ways, either passing the object:
```
result, call = so.simple_operation.call(self=so, input_value="example input...", other_val="other item")
```

Or wrapping the parameters into a dict, but either seems less than ideal?

**Comment by andrewtruong** [comment]
Hey @travis-the-dragon , sorry you're running into this issue

This happens because of a limitation of the `call` special func when used with vanilla python classes.  I'm going to see if there's a quick way to fix this, but in the mean time, these alternatives might be helpful:

1. You can inherit from `weave.Object`, which will automatically pass `self` for you, e.g.
```
class SweetObj(weave.Object): ...
```

2. If you just need the current call, you can do something like:
```
class SweetObj:
    @weave.op
    def test(self):
        call = weave.get_current_call()
        return call
```

That should return a call object like so:
![image](https://github.com/user-attachments/assets/0892cf09-2da5-403e-8b1a-f6b5e490e361)

**Comment by travis-the-dragon** [comment]
Ah, ok. And this might just be my inexperience with python showing. So apologies. 
Inheriting from `weave.Object` worked, but I did have to get around a Pydantic error with the object attributes. So this works:

```
from pydantic import BaseModel, Field

import weave
weave.init("junk-stuff")

class SweetObj(weave.Object):
    # _name: str
    name: str = Field(default="sweet") # To adhere to Pydantic from weave
    
    # def __init__(self):
        # self._name = "sweet"
    
    @weave.op()
    def simple_operation(self, input_value, other_val):
        return f"Processed {input_value}, also {other_val}"

so = SweetObj()
result, call = so.simple_operation.call(input_value="example input...", other_val="other item")
```

I also got the `get_current_call` working with some modifications:

```
class SweetObj(weave.Object):
    name: str = Field(default="sweet") # To adhere to Pydantic from weave
    
    @weave.op()
    def simple_operation(self, input_value, other_val):
        return f"Processed {input_value}, also {other_val}"
    
    @weave.op()
    def other_operation(self, input1, input2):
        output = f"Other processed {input1}, {input2}"
        call = weave.get_current_call()
        current_call = weave.get_current_call()
        call_id = current_call.id
        return output, call_id

so = SweetObj()

```

So I think one of those will work. 
Thank you!
