### ISSUE TITLE
LiteLLM integration is broken

### ISSUE THREAD

**Issue by tcapelle** [wandb/weave#2830]
Script to reproduce:

```python
# pip install weave litellm
import weave
from litellm import completion

weave.init("litellm_bug")

class Model(weave.Model):
    system_prompt: str = "You are a helpful assistant."

    @weave.op()
    def predict(self, prompt: str) -> str:
        return completion(
            messages=[{"role": "system", "content": self.system_prompt}, {"role": "user", "content": prompt}],
            model="gpt-4o")

model = Model()
output = model.predict("Hello, world!")
print(output)
```

Stack Trace:
```python
Traceback (most recent call last):
  File "/Users/tcapelle/work/evalForge/litellm_bug.py", line 23, in <module>
    output = model.predict("Hello, world!")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/site-packages/weave/trace/op.py", line 575, in wrapper
    res, _ = _do_call(
             ^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/site-packages/weave/trace/op.py", line 393, in _do_call
    execute_result = _execute_call(
                     ^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/site-packages/weave/trace/op.py", line 309, in _execute_call
    handle_exception(e)
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/site-packages/weave/trace/op.py", line 307, in _execute_call
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/work/evalForge/litellm_bug.py", line 18, in predict
    return completion(
           ^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/site-packages/litellm/utils.py", line 1013, in wrapper
    raise e
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/site-packages/litellm/utils.py", line 797, in wrapper
    logging_obj, kwargs = function_setup(
                          ^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/site-packages/litellm/utils.py", line 612, in function_setup
    raise e
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/site-packages/litellm/utils.py", line 581, in function_setup
    logging_obj = LiteLLMLogging(
                  ^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/site-packages/litellm/litellm_core_utils/litellm_logging.py", line 236, in __init__
    self.messages = copy.deepcopy(messages)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 196, in _deepcopy_list
    append(deepcopy(a, memo))
           ^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tcapelle/miniforge3/envs/weave/lib/python3.12/copy.py", line 151, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle '_thread.RLock' object
```

Removing the `self.system_prompt` usage from ~`weave.Model`~ `predict` seems to fix it?!

## Claude response

I see the issue. The error occurs because LiteLLM is trying to do a deep copy of the messages, and there seems to be a threading lock object getting caught up in the attribute reference. This is likely due to how Weave handles class attributes internally.

**Comment by kdaniel21** [comment]
I am experiencing the same issue. An even quicker reproduction would be something like this:
```
import copy
import typing

class Model(weave.Model):
    system_prompt: typing.List[typing.Any] = []

    @weave.op()
    def predict(self) -> str:
        copy.deepcopy(self.system_prompt)
        return
    
model = Model()
model.predict()
```

It seems like that removing the `op` decorator resolves the issue (although it also removes functionality).

**Comment by andrewtruong** [comment]
Should be resolved with this set of PRs:
https://github.com/wandb/weave/pull/2868
