### ISSUE TITLE
No module named 'weave_query'

### ISSUE THREAD

**Issue by R0bynZhu** [wandb/weave#2966]
Python version: 3.11

What did i do:
1. pip install weave
2. pip install fastapi uvicorn
3. weave serve <my weave op>

What i got:
`
Traceback (most recent call last):
  File "/Users/xxx/pago/mywandb/.conda/bin/weave", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/xxx/pago/mywandb/.conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/pago/mywandb/.conda/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/xxx/pago/mywandb/.conda/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/pago/mywandb/.conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/pago/mywandb/.conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/pago/mywandb/.conda/lib/python3.11/site-packages/weave/trace/cli.py", line 52, in serve
    api.serve(
  File "/Users/xxx/pago/mywandb/.conda/lib/python3.11/site-packages/weave/trace/api.py", line 208, in serve
    from weave.trace.serve_fastapi import object_method_app
  File "/Users/xxx/pago/mywandb/.conda/lib/python3.11/site-packages/weave/trace/serve_fastapi.py", line 8, in <module>
    from weave_query import cache, op_args, pyfunc_type_util, weave_pydantic  # type: ignore
ModuleNotFoundError: No module named 'weave_query'
`

**Comment by jwlee64** [comment]
Hi @R0bynZhu,
Currently we are not supporting weave serve for the foreseeable future though we will bring it back at some point. weave_query is a dependency that is intentionally not packaged anymore to decrease the overall package size and the download time. I can note this bug and the request for this feature to be fixed.

**Comment by TeoZosa** [comment]
@jwlee64 I ran into this myself . Would it be a bad idea to at least update the docs and Weave serve references in the Models UI page? I almost showed this in a team demo which would've killed some credibility for the tool.

![Image](https://github.com/user-attachments/assets/ddad29f7-ca92-4b08-a80e-1a9a58fbbae8)
![Image](https://github.com/user-attachments/assets/2d3721c8-cccc-46b8-ba11-9f71fce24277)

**Comment by jwlee64** [comment]
Hi @TeoZosa, we will be removing the references within the app and docs today, and looking into what it takes to fix. Thank you for the patience.

**Comment by TeoZosa** [comment]
@jwlee64 sounds good! Likewise, thanks for your patience with the influx of feedback 😄

**Comment by piantic** [comment]
Hi, I also faced this issue. I will wait for supports or updates.

**Comment by andrewtruong** [comment]
The weave_query dir was removed; this should be resolved
