### ISSUE TITLE
python Version Error

### ISSUE THREAD

**Issue by pandya6988** [wandb/weave#32]
I have a Linux machine. 
`pip install weave` throws me an error.

```
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-yfc8hmif/weave_c37d95621c4049e2941ad6a0cd61fdaf/setup.py", line 24, in <module>
          raise RuntimeError("Python version 2.6 or 2.7 required.")
      RuntimeError: Python version 2.6 or 2.7 required.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

Python 2.6 or 2.7 requires.  I don't think this should be an issue. I am using python 3.8. 

Thanks for your help. :)

**Comment by pandya6988** [comment]
python3.9 with following command solved the problem. 
`python -m pip install weave`

Thanks :)
