### ISSUE TITLE
`Something went wrong. Check the javascript console.` when making a new panel.

### ISSUE THREAD

**Issue by Fraser-Greenlee** [wandb/weave#540]
Tried locally and on Google Collab `Weave Quickstart`.

All I do is press the "Add New Panel" button.

<img width="1676" alt="Screenshot 2023-09-08 at 14 39 21" src="https://github.com/wandb/weave/assets/8402500/1e4ff901-e68e-414c-863d-ecabedeb4b1b">

Got this JS error:
```
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'config')
    at PagePanel.tsx:606:32
    at PagePanel.tsx:281:31
    at Jh (react-dom.production.min.js:158:387)
    at Kh (react-dom.production.min.js:159:447)
    at Object.useState (react-dom.production.min.js:174:261)
    at react_production_min.useState (react.production.min.js:23:281)
    at PagePanel (PagePanel.tsx:255:31)
    at Ch (react-dom.production.min.js:157:137)
    at li$1 (react-dom.production.min.js:180:154)
    at ck (react-dom.production.min.js:269:343)
```

**Comment by tssweeney** [comment]
Hello @Fraser-Greenlee - thank you for the bug report - this should be fixed in the latest release via this PR: https://github.com/wandb/weave/pull/599
